<?php
/**
 * Created by PhpStorm.
 * User: Garrinar
 * Date: 06.05.2016
 * Time: 12:15
 */

namespace Garrinar\Filesystem\Distributed;

use League\Flysystem\Adapter\Local;
use League\Flysystem\Config;
use SplFileInfo;

class Adapter extends Local
{
    public function applyPathPrefix($path)
    {
        $path = $this->applyDistributedPathPrefix($path);
        return $path;
    }

    public function applyDistributedPathPrefix($path)
    {
        return parent::applyPathPrefix($this->getDistributedPrefix($path).$path);
    }

    public function createDistributedPathDirs($md5FileName)
    {
        $prefixes = collect([
            mb_substr($md5FileName, 0, 3),
            mb_substr($md5FileName, 3, 3),
            mb_substr($md5FileName, 6, 3),
        ]);
        $dirPath = '';
        $prefixes->each(function($prefix) use (&$dirPath) {
            $dirPath .= $this->pathSeparator.$prefix;
            $fullPath = parent::getPathPrefix().$dirPath;
            if(!is_dir($fullPath)) {
                @mkdir(parent::getPathPrefix() . $dirPath);
            }
        });

        return $dirPath.$this->pathSeparator;
    }

    public function write($path, $contents, Config $config)
    {
        /** @var Adapter $file */
        $oldName = $path;
        $path = md5($oldName.microtime(true));
        $this->createDistributedPathDirs($path);
        $file = parent::write($path, $contents, $config);
        if(is_array($file)) {
            $file['name'] = $file['path'];
            $file['path'] = $this->applyDistributedPathPrefix($path);
            $file['old_name'] = $oldName;
            dd($file, $path);
            return $file;
        }
        return false;
    }

    public function update($path, $contents, Config $config)
    {
        return parent::update($path, $contents, $config); // TODO: Change the autogenerated stub
    }

    public function rename($path, $newpath)
    {
        return parent::rename($path, $newpath); // TODO: Change the autogenerated stub
    }

    public function copy($path, $newpath)
    {
        return parent::copy($path, $newpath); // TODO: Change the autogenerated stub
    }

    protected function getFilePath(SplFileInfo $file)
    {
        dd('fp');
        return parent::getFilePath($file); // TODO: Change the autogenerated stub
    }


}