<?php

namespace Garrinar\Filesystem\Distributed;

use League\Flysystem\Util;
use Symfony\Component\Finder\Finder;
use League\Flysystem\Filesystem as FlySystem;
use League\Flysystem\AdapterInterface;

class Filesystem extends FlySystem
{
    /**
     * Constructor.
     *
     * @param AdapterInterface $adapter
     * @param Config|array $config
     */
    public function __construct(AdapterInterface $adapter, $config = null)
    {
        parent::__construct($adapter, $config);
    }

    public function write($path, $contents, array $config = [])
    {
        dd($path);
        return parent::write($path, $contents, $config); // TODO: Change the autogenerated stub
    }

    public function update($path, $contents, array $config = [])
    {
        dd($path);
        return parent::update($path, $contents, $config); // TODO: Change the autogenerated stub
    }


}
